workflows:
  android-release:
    name: Android Release Build
    environment:
      flutter: stable
scripts:
  - flutter create .
  - |
      sed -i '/<manifest/a\
      <uses-permission android:name="android.permission.READ_SMS"/>\
      <uses-permission android:name="android.permission.RECEIVE_SMS"/>\
      <uses-permission android:name="android.permission.READ_PHONE_STATE"/>' \
      android/app/src/main/AndroidManifest.xml
  - flutter pub get
  - flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
