workflows:
  generate-project:
    name: Generate Full Flutter Project
    max_build_duration: 20

    environment:
      flutter: stable

    scripts:
      - flutter create expensinfo_full

    artifacts:
      - expensinfo_full/**

  android-release:
    name: Android Release Build
    max_build_duration: 60

    environment:
      flutter: stable

    scripts:
      - flutter pub get
      - flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
